# Generated by Django 4.2.5 on 2023-10-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('moderator', 'Moderator'), ('member', 'Member')], default='member', max_length=30, verbose_name='role'),
        ),
    ]
