version: '3'

services:
  redis:
    image: redis:latest
    ports:
    - '6379:6379'

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'

  app:
    build: .
    tty: true
    command: sh -c "python manage.py migrate &&
         python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    depends_on:
      - db

  celery:
    build: .
    tty: true
    command:
      celery -A config worker -l INFO
    depends_on:
      - redis
      - app

  celery_beat:
    build: .
    tty: true
    command:
      celery -A config beat -l INFO -S django
    depends_on:
      - redis
      - app



volumes:
  pg_data: