# Generated by Django 4.2.5 on 2023-10-16 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_subscriber_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='payments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 13, 3, 33, 43598, tzinfo=datetime.timezone.utc), verbose_name='дата подписки'),
        ),
    ]
