# Generated by Django 4.2.5 on 2023-10-16 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_course_payments_alter_subscriber_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='payments',
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 13, 20, 9, 456994, tzinfo=datetime.timezone.utc), verbose_name='дата подписки'),
        ),
    ]
