# Generated by Django 4.2.5 on 2023-10-18 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_alter_subscriber_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 18, 7, 48, 0, 812010, tzinfo=datetime.timezone.utc), verbose_name='дата подписки'),
        ),
    ]
