# Generated by Django 4.2.5 on 2023-10-19 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_alter_subscriber_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 19, 7, 23, 32, 384669, tzinfo=datetime.timezone.utc), verbose_name='дата подписки'),
        ),
    ]
