# Generated by Django 4.2.5 on 2023-10-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_alter_subscriber_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='course/', verbose_name='превью'),
        ),
    ]
