# Generated by Django 4.2.5 on 2023-10-17 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesson', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='owner',
        ),
        migrations.AddField(
            model_name='lesson',
            name='owner',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='владелец'),
        ),
    ]
